DROP  TRIGGER IF exists STOP_ORDERS_BEFORE_UPD_TR;
DROP  TRIGGER IF exists TRANSACTION_BEFORE_UPD_TR;
DROP  TRIGGER IF exists EXORDERS_BEFORE_UPD_TR;
DELIMITER ||
 CREATE TRIGGER TRANSACTION_BEFORE_UPD_TR
BEFORE UPDATE ON TRANSACTION
FOR EACH ROW
BEGIN
  IF (NEW.status_id <> OLD.status_id) THEN
      SET new.status_modification_date = CURRENT_TIMESTAMP;
    END IF;
END;
|| CREATE TRIGGER EXORDERS_BEFORE_UPD_TR
BEFORE UPDATE ON EXORDERS
FOR EACH ROW
BEGIN
    IF (NEW.status_id <> OLD.status_id) THEN
      SET new.status_modification_date = CURRENT_TIMESTAMP;
    END IF;
  END;
|| CREATE TRIGGER STOP_ORDERS_BEFORE_UPD_TR
BEFORE UPDATE ON STOP_ORDERS
FOR EACH ROW
  BEGIN
    IF (NEW.status_id <> OLD.status_id) THEN
      SET new.date_modification = CURRENT_TIMESTAMP;
    END IF;
  END;
||
DELIMITER ;