INSERT INTO USER_ROLE_REPORT_GROUP_FEATURE (id, name) VALUES (1, 'ADMIN');
INSERT INTO USER_ROLE_REPORT_GROUP_FEATURE (id, name) VALUES (4, 'BOT');
INSERT INTO USER_ROLE_REPORT_GROUP_FEATURE (id, name) VALUES (3, 'TRADER');
INSERT INTO USER_ROLE_REPORT_GROUP_FEATURE (id, name) VALUES (2, 'USER');
