INSERT INTO USER_ROLE_BUSINESS_FEATURE (id, name) VALUES (1, 'ADMIN');
INSERT INTO USER_ROLE_BUSINESS_FEATURE (id, name) VALUES (2, 'USER');
INSERT INTO USER_ROLE_BUSINESS_FEATURE (id, name) VALUES (3, 'EXCHANGE');
INSERT INTO USER_ROLE_BUSINESS_FEATURE (id, name) VALUES (4, 'VIP_USER');
INSERT INTO USER_ROLE_BUSINESS_FEATURE (id, name) VALUES (5, 'TRADER');
INSERT INTO USER_ROLE_BUSINESS_FEATURE (id, name) VALUES (6, 'BOT');
INSERT INTO USER_ROLE_BUSINESS_FEATURE (id, name) VALUES (7, 'MARKET_MAKER');
INSERT INTO USER_ROLE_BUSINESS_FEATURE (id, name) VALUES (9, 'OUTER_MARKET_BOT');
