INSERT INTO USER_ROLE_GROUP_FEATURE (id, name) VALUES (1, 'ADMINS');
INSERT INTO USER_ROLE_GROUP_FEATURE (id, name) VALUES (2, 'USERS');
INSERT INTO USER_ROLE_GROUP_FEATURE (id, name) VALUES (3, 'BOT');
