package me.exrates.model.enums;

/**
 * Created by Maks on 30.08.2017.
 */
public enum RefreshObjectsEnum {

    MY_TRADES, ALL_TRADES, CHART, STATISTICS, CURRENCIES_STATISTIC, MAIN_CURRENCIES_STATISTIC, ICO_CURRENCIES_STATISTIC, MAIN_CURRENCY_STATISTIC, ICO_CURRENCY_STATISTIC
}
