package me.exrates.model.enums;

public enum UserEventEnum {

    REGISTER, LOGIN_SUCCESS, RESET_PASSWORD, CHANGE_PASSWORD, WITHDRAW, TRADE, REFILL_ADDRESS, REFILL_REQUEST, TRANSFER_SEND, TRANSFER_CODE_ACCEPT
}
