INSERT INTO USER_ROLE (id, name) VALUES (6, 'EXCHANGE');
INSERT INTO USER_ROLE (id, name) VALUES (7, 'VIP_USER');

ALTER TABLE COMMISSION
  DROP COLUMN `editable`,
  ADD COLUMN `user_role` INT(40) NULL AFTER `date`,
  ADD INDEX `commission_fk_usr_role_idx` (`user_role` ASC);
ALTER TABLE COMMISSION
  ADD CONSTRAINT `commission_fk_usr_role`
FOREIGN KEY (`user_role`)
REFERENCES USER_ROLE (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

UPDATE COMMISSION SET user_role = 4;

CREATE TEMPORARY TABLE IF NOT EXISTS TEMP_COMM AS (SELECT * FROM COMMISSION);

INSERT INTO COMMISSION(operation_type, date, value, user_role) SELECT TEMP_COMM.operation_type,
  CURRENT_TIMESTAMP, TEMP_COMM.value, USER_ROLE.id
FROM TEMP_COMM
JOIN USER_ROLE WHERE USER_ROLE.id != 4 AND USER_ROLE.id != 5;

DROP TEMPORARY TABLE IF EXISTS TEMP_COMM;