ALTER TABLE USER_ROLE_SETTINGS ADD considered_for_price_range TINYINT(1) DEFAULT '0' NOT NULL;
ALTER TABLE BOT_LAUNCH_SETTINGS ADD consider_user_orders TINYINT(1) DEFAULT 0 NOT NULL;
ALTER TABLE BOT_LAUNCH_SETTINGS
  MODIFY COLUMN consider_user_orders TINYINT(1) NOT NULL DEFAULT 0 AFTER is_enabled;