
ALTER TABLE MERCHANT_CURRENCY ADD COLUMN min_sum DOUBLE(40,9) DEFAULT 0;
UPDATE MERCHANT_CURRENCY SET min_sum = 0.01 WHERE merchant_id = 1 AND currency_id = 1;

ALTER TABLE TRANSACTION ADD COLUMN operation_type INT;

UPDATE TRANSACTION SET operation_type = 1 WHERE transaction_type = 1;
UPDATE TRANSACTION SET operation_type = 2 WHERE transaction_type = 2;

ALTER TABLE TRANSACTION DROP COLUMN transaction_type;
ALTER TABLE TRANSACTION ADD FOREIGN KEY TRANSACTION(operation_type) REFERENCES OPERATION_TYPE(id) ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE TRANSACTION ADD COLUMN currency_id INT;
UPDATE TRANSACTION SET currency_id = (SELECT CURRENCY.id FROM WALLET JOIN CURRENCY ON WALLET.currency_id = CURRENCY.id WHERE WALLET.id = TRANSACTION.wallet_id);
ALTER TABLE TRANSACTION ADD FOREIGN KEY TRANSACTION_CURRENCY_ID(currency_id) REFERENCES CURRENCY(id) ON UPDATE CASCADE ON DELETE RESTRICT ;



ALTER TABLE TRANSACTION ADD COLUMN merchant_id INT;
UPDATE TRANSACTION SET merchant_id = 1;
ALTER TABLE TRANSACTION ADD FOREIGN KEY Merchant_id(merchant_id) REFERENCES MERCHANT(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE COMPANY_TRANSACTION ADD COLUMN commission_id INT;
UPDATE COMPANY_TRANSACTION set commission_id = (SELECT id FROM COMMISSION WHERE COMPANY_TRANSACTION.operation_type_id
 = COMMISSION.operation_type);

CREATE TABLE DATABASE_PATCH (version VARCHAR(50), date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, patched tinyint(1) DEFAULT NULL);
INSERT INTO DATABASE_PATCH (version,patched) VALUES ("patch_07_modified_transaction_table",0);

ALTER TABLE COMPANY_WALLET ADD COLUMN balance DOUBLE(40,9) NOT NULL DEFAULT 0;
ALTER TABLE COMPANY_WALLET ADD COLUMN commission_balance DOUBLE(40,9) NOT NULL DEFAULT 0;
ALTER TABLE TRANSACTION ADD COLUMN commission_amount DOUBLE (40,9) NOT NULL AFTER amount;
ALTER TABLE TRANSACTION CHANGE COLUMN date datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE TRANSACTION DROP FOREIGN KEY transaction_ibfk_2;
ALTER TABLE TRANSACTION CHANGE COLUMN operation_type operation_type_id INT;
ALTER TABLE TRANSACTION ADD FOREIGN KEY TRANSACTION(operation_type_id) REFERENCES OPERATION_TYPE(id) ON UPDATE CASCADE ON DELETE RESTRICT ;
ALTER TABLE TRANSACTION CHANGE COLUMN  datetime datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER merchant_id;
ALTER TABLE TRANSACTION CHANGE COLUMN  wallet_id user_wallet_id INT;
ALTER TABLE TRANSACTION ADD COLUMN company_wallet_id INT AFTER user_wallet_id;
ALTER TABLE TRANSACTION ADD FOREIGN KEY TRANSACTION_COMPANY_WALLET(company_wallet_id) REFERENCES COMPANY_WALLET(id) ON UPDATE CASCADE ON DELETE RESTRICT ;
UPDATE TRANSACTION SET company_wallet_id = 2;
ALTER TABLE TRANSACTION CHANGE COLUMN  company_wallet_id company_wallet_id INT NOT NULL ;
ALTER TABLE TRANSACTION CHANGE COLUMN user_wallet_id user_wallet_id INT NOT NULL ;
ALTER TABLE TRANSACTION CHANGE COLUMN amount amount DOUBLE(40,9) NOT NULL ;
ALTER TABLE TRANSACTION CHANGE COLUMN  operation_type_id operation_type_id INT NOT NULL ;
ALTER TABLE TRANSACTION CHANGE COLUMN currency_id currency_id INT NOT NULL ;
ALTER TABLE TRANSACTION CHANGE COLUMN merchant_id merchant_id INT NOT NULL ;
DROP TABLE COMPANY_TRANSACTION;
