CREATE TABLE MERCHANT_SPEC_PARAMETERS (
  `id` int(40) NOT NULL AUTO_INCREMENT,
  `merchant_id` int(40) NOT NULL,
  `param_name` VARCHAR(200) NOT NULL,
  `param_value` VARCHAR(1000),
  PRIMARY KEY (`id`),
  KEY `MERCHANT_SPEC_PARAMETERS_merchant_id` (`merchant_id`),
  CONSTRAINT `fk_MERCHANT_SPEC_PARAMETERS_merchant_id` FOREIGN KEY (`merchant_id`) REFERENCES `MERCHANT` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
