CREATE TABLE CHAT_RU (
  id INT PRIMARY KEY ,
  user_id INT NOT NULL ,
  body VARCHAR(256) NOT NULL,
  FOREIGN KEY CHAT_RU(user_id) REFERENCES USER(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE CHAT_EN (
  id INT PRIMARY KEY ,
  user_id INT NOT NULL ,
  body VARCHAR(256) NOT NULL,
  FOREIGN KEY CHAT_RU(user_id) REFERENCES USER(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE CHAT_CN (
  id INT PRIMARY KEY ,
  user_id INT NOT NULL ,
  body VARCHAR(256) NOT NULL,
  FOREIGN KEY CHAT_RU(user_id) REFERENCES USER(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

INSERT INTO DATABASE_PATCH VALUES ('patch_48_added_chats_tables', default, 1);