ALTER TABLE TEMPORAL_TOKEN
DROP FOREIGN KEY `fk_REGISTRATION_TOKEN_USER1`;

ALTER TABLE TEMPORAL_TOKEN
ADD CONSTRAINT `fk_REGISTRATION_TOKEN_USER1` 
    FOREIGN KEY (`user_id`) REFERENCES USER (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;

INSERT INTO DATABASE_PATCH VALUES('patch_26_changed_foreignkey_for_temporal_token',default,1);