INSERT INTO CURRENCY_PAIR VALUES (22, 4, 8, 'BTC/CNY', 2, 0);
INSERT INTO CURRENCY_PAIR VALUES (23, 6, 8, 'EDRC/CNY', 6, 0);
INSERT INTO CURRENCY_PAIR VALUES (24, 2, 8, 'USD/CNY', 10, 0);

UPDATE CURRENCY_PAIR SET pair_order = 3 WHERE id = 12;
UPDATE CURRENCY_PAIR SET pair_order = 4 WHERE id = 11;
UPDATE CURRENCY_PAIR SET pair_order = 5 WHERE id = 21;
UPDATE CURRENCY_PAIR SET pair_order = 7 WHERE id = 13;
UPDATE CURRENCY_PAIR SET pair_order = 8 WHERE id = 3;
UPDATE CURRENCY_PAIR SET pair_order = 9 WHERE id = 19;
UPDATE CURRENCY_PAIR SET pair_order = 11 WHERE id = 2;

INSERT INTO DATABASE_PATCH VALUES('patch_58_add_CNY_currency_pairs',default,1);
