INSERT INTO CHAT_EN (user_id, message) VALUES (1, 'Blablablabla');
INSERT INTO CHAT_EN (user_id, message) VALUES (1, 'Blabl123123la');

CREATE TABLE CHAT_RU (
  id INT PRIMARY KEY ,
  user_id INT NOT NULL ,
  body VARCHAR(256) NOT NULL,
  FOREIGN KEY CHAT_RU(user_id) REFERENCES USER(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE CHAT_EN (
  id INT PRIMARY KEY ,
  user_id INT NOT NULL ,
  body VARCHAR(256) NOT NULL,
  FOREIGN KEY CHAT_RU(user_id) REFERENCES USER(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE CHAT_CN (
  id INT PRIMARY KEY ,
  user_id INT NOT NULL ,
  body VARCHAR(256) NOT NULL,
  FOREIGN KEY CHAT_RU(user_id) REFERENCES USER(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

DROP TABLE CHAT_EN;
DROP TABLE CHAT_RU;
DROP TABLE CHAT_CN;


SELECT * FROM CHAT_RU;
SELECT * FROM CHAT_CN;
SELECT * FROM CHAT_EN;


SELECT c.user_id, c.message, c.datetime, USER.nickname from CHAT_EN as c INNER JOIN USER ON c.user_id = USER.id ORDER BY c.datetime DESC LIMIT 50;