ALTER TABLE birzha.REFERRAL_USER_GRAPH DROP FOREIGN KEY referral_user_graph_ibfk_1;
ALTER TABLE birzha.REFERRAL_USER_GRAPH
  ADD CONSTRAINT referral_user_graph_ibfk_1
FOREIGN KEY (child) REFERENCES USER (id) ON DELETE CASCADE ON UPDATE CASCADE;