INSERT INTO TRANSACTION_SOURCE_TYPE(id, name) VALUES (9, 'WITHDRAW');
ALTER TABLE TRANSACTION MODIFY source_type
  ENUM('ORDER', 'MERCHANT', 'REFERRAL', 'ACCRUAL', 'MANUAL', 'USER_TRANSFER', 'INVOICE', 'BTC_INVOICE', 'WITHDRAW');


SELECT COUNT(*) FROM TRANSACTION JOIN withdraw_request ON withdraw_request.transaction_id = transaction.id;

UPDATE TRANSACTION
  JOIN WITHDRAW_REQUEST ON WITHDRAW_REQUEST.transaction_id = TRANSACTION.id
SET TRANSACTION.source_type = 'WITHDRAW', TRANSACTION.source_id = WITHDRAW_REQUEST.transaction_id;
;