

CREATE TABLE IF NOT EXISTS `birzha`.`REGISTRATION_TOKEN` (
  `id` INT(40) NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  `user_id` INT(40) NOT NULL,
  `expired` TINYINT(1) NOT NULL DEFAULT 0,
  `date_creation` TIMESTAMP NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB

ALTER TABLE `birzha`.`REGISTRATION_TOKEN` 
CHANGE COLUMN `date_creation` `date_creation` TIMESTAMP NULL DEFAULT now() ,
ADD INDEX `fk_REGISTRATION_TOKEN_USER1_idx` (`user_id` ASC);

ALTER TABLE `birzha`.`REGISTRATION_TOKEN` 
ADD CONSTRAINT `fk_REGISTRATION_TOKEN_USER1`
  FOREIGN KEY (`user_id`)
  REFERENCES `birzha`.`USER` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

INSERT DATABASE_PATCH VALUES('patch_15_added_data_currency_pairs',default,1);
INSERT DATABASE_PATCH VALUES('patch_16_createRegistrationToken',default,1);