UPDATE CURRENCY SET description = 'Russian Ruble' WHERE name = 'RUB';
UPDATE CURRENCY SET description = 'US Dollar' WHERE name = 'USD';
UPDATE CURRENCY SET description = 'Euro' WHERE name = 'EUR';
UPDATE CURRENCY SET description = 'Bitcoin' WHERE name = 'BTC';
UPDATE CURRENCY SET description = 'Litecoin' WHERE name = 'LTC';
UPDATE CURRENCY SET description = 'EDR-coin' WHERE name = 'EDRC';
UPDATE CURRENCY SET description = 'Ukrainian Hryvnia' WHERE name = 'UAH';
UPDATE CURRENCY SET description = 'Chinese Yuan Renminbi' WHERE name = 'CNY';
UPDATE CURRENCY SET description = 'Indonesian Rupiah' WHERE name = 'IDR';
UPDATE CURRENCY SET description = 'Thai Baht' WHERE name = 'THB';
UPDATE CURRENCY SET description = 'Indian Rupee' WHERE name = 'INR';
UPDATE CURRENCY SET description = 'Nigerian Naira' WHERE name = 'NGN';
UPDATE CURRENCY SET description = 'Ethereum' WHERE name = 'ETH';
UPDATE CURRENCY SET description = 'Vietnamese Dong' WHERE name = 'VND';
UPDATE CURRENCY SET description = 'Turkish Lira' WHERE name = 'TRY';
UPDATE CURRENCY SET description = 'Ethereum Classic' WHERE name = 'ETC';
UPDATE CURRENCY SET description = 'Emirati Dirham' WHERE name = 'AED';
UPDATE CURRENCY SET description = 'Ripple' WHERE name = 'XRP';
UPDATE CURRENCY SET description = 'Stellar Lumens' WHERE name = 'XLM';
UPDATE CURRENCY SET description = 'NEM' WHERE name = 'XEM';
UPDATE CURRENCY SET description = 'Augur' WHERE name = 'REP';