CREATE TABLE EDC_TEMP_ACCOUNT (
  transaction_id INT PRIMARY KEY NOT NULL,
  wif_priv_key VARCHAR(256) NOT NULL ,
  pub_key VARCHAR(256) NOT NULL ,
  brain_priv_key VARCHAR(256) NOT NULL ,
  FOREIGN KEY EDC_TEMP_ACCOUNT(transaction_id) REFERENCES TRANSACTION(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);

SELECT * FROM TRANSACTION ORDER BY datetime DESC ;

SELECT * FROM PENDING_PAYMENT WHERE invoice_id = 36191;
SELECT * FROM EDC_TEMP_ACCOUNT;

INSERT INTO EDC_TEMP_ACCOUNT (transaction_id, wif_priv_key, pub_key, brain_priv_key) VALUES (36183 ,'abc', 'abc', 'abc');
