
 INSERT DATABASE_PATCH VALUES('patch_12_added_data_currencies',default,1);
 
 DELETE FROM TRANSACTION;
 DELETE FROM WALLET;
 DELETE FROM COMPANY_WALLET;
 DELETE FROM CURRENCY;
 DELETE FROM ORDERS;
 INSERT CURRENCY VALUES(1,'RUB',NULL);
 INSERT CURRENCY VALUES(2,'USD',NULL);
 INSERT CURRENCY VALUES(3,'EUR',NULL);
 INSERT CURRENCY VALUES(4,'BTC',NULL);
 INSERT CURRENCY VALUES(5,'LTC',NULL);
 
 
 INSERT COMPANY_WALLET VALUES(1,1,0,0);
 INSERT COMPANY_WALLET VALUES(2,2,0,0);
 INSERT COMPANY_WALLET VALUES(3,3,0,0);
 INSERT COMPANY_WALLET VALUES(4,4,0,0);
 INSERT COMPANY_WALLET VALUES(5,5,0,0);
 