ALTER TABLE REFILL_REQUEST
  ADD COLUMN inner_transfer_hash VARCHAR(200) NULL;

ALTER TABLE MERCHANT
  ADD COLUMN to_main_account_transferring_confirm_needed BOOLEAN DEFAULT FALSE;

ALTER TABLE MERCHANT
  ADD COLUMN withdraw_transferring_confirm_needed BOOLEAN DEFAULT FALSE;

ALTER TABLE MERCHANT
  ADD COLUMN generate_additional_refill_address_available BOOLEAN DEFAULT FALSE;

ALTER TABLE MERCHANT
  ADD COLUMN additional_tag_for_withdraw_address_is_used BOOLEAN DEFAULT FALSE;
  
ALTER TABLE WITHDRAW_REQUEST
	ADD COLUMN destination_tag VARCHAR(100) NULL DEFAULT NULL AFTER admin_holder_id;


INSERT INTO REFILL_REQUEST_STATUS (id, name) VALUES (15, 'ON_INNER_TRANSFERRING');
INSERT INTO REFILL_REQUEST_STATUS (id, name) VALUES (16, 'WAITING_REVIEWING');
INSERT INTO REFILL_REQUEST_STATUS (id, name) VALUES (17, 'TAKEN_FOR_REFILL');

INSERT INTO WITHDRAW_REQUEST_STATUS (id, name) VALUES (13, 'ON_BCH_EXAM');
INSERT INTO WITHDRAW_REQUEST_STATUS (id, name) VALUES (14, 'WAITING_REVIEWING');
INSERT INTO WITHDRAW_REQUEST_STATUS (id, name) VALUES (15, 'TAKEN_FOR_WITHDRAW');

ALTER TABLE WITHDRAW_REQUEST DROP COLUMN transaction_id;