ALTER TABLE INVOICE_REQUEST
	ADD COLUMN status_update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE INVOICE_REQUEST
	ADD INDEX invoice_request_status_id_status_update_date (status_update_date, invoice_request_status_id);

CREATE TABLE TRANSACTION_SOURCE_TYPE (
	id INT(40) NOT NULL AUTO_INCREMENT,
	name VARCHAR(45) NOT NULL,
	PRIMARY KEY (id),
	UNIQUE INDEX id_UNIQUE (id)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;

INSERT INTO TRANSACTION_SOURCE_TYPE (id, name) VALUES (1, 'ORDER');
INSERT INTO TRANSACTION_SOURCE_TYPE (id, name) VALUES (2, 'MERCHANT');
INSERT INTO TRANSACTION_SOURCE_TYPE (id, name) VALUES (3, 'REFERRAL');
INSERT INTO TRANSACTION_SOURCE_TYPE (id, name) VALUES (4, 'ACCRUAL');
INSERT INTO TRANSACTION_SOURCE_TYPE (id, name) VALUES (5, 'MANUAL');
INSERT INTO TRANSACTION_SOURCE_TYPE (id, name) VALUES (6, 'USER_TRANSFER');
INSERT INTO TRANSACTION_SOURCE_TYPE (id, name) VALUES (7, 'INVOICE');

ALTER TABLE MERCHANT
	ADD COLUMN transaction_source_type_id INT(2) NOT NULL DEFAULT '2';

ALTER TABLE MERCHANT
	ADD CONSTRAINT FK_merchant_transaction_source_type FOREIGN KEY (transaction_source_type_id) REFERENCES TRANSACTION_SOURCE_TYPE (`id`);

UPDATE MERCHANT SET transaction_source_type_id=7 WHERE  id=12;