RENAME TABLE PENDING_BLOCKCHAIN_PAYMENT TO PENDING_PAYMENT;

ALTER TABLE PENDING_PAYMENT DROP COLUMN amount,
CHANGE address transaction_hash VARCHAR(64) NOT NULL,
ADD COLUMN address VARCHAR(64);


SELECT *
FROM TRANSACTION WHERE TRANSACTION.user_wallet_id = 13;