ALTER TABLE WITHDRAW_REQUEST
	ADD COLUMN currency_id INT(11) NULL DEFAULT NULL,
	ADD COLUMN user_id INT(11) NULL DEFAULT NULL,
	ADD COLUMN commission INT(11) NULL DEFAULT NULL,
	ADD COLUMN merchant_id INT(11) NULL DEFAULT NULL,
	ADD COLUMN admin_holder_id INT(11) NULL DEFAULT NULL;

ALTER TABLE WITHDRAW_REQUEST
	ADD CONSTRAINT FK_withdraw_request_currency FOREIGN KEY (currency_id) REFERENCES CURRENCY (id);

ALTER TABLE WITHDRAW_REQUEST
	ADD CONSTRAINT FK_withdraw_request_merchant FOREIGN KEY (merchant_id) REFERENCES MERCHANT (id);

ALTER TABLE WITHDRAW_REQUEST
	ADD CONSTRAINT FK_withdraw_request_user FOREIGN KEY (user_id) REFERENCES USER (id);

ALTER TABLE WITHDRAW_REQUEST
	ADD CONSTRAINT FK_withdraw_request_commission FOREIGN KEY (commission_id) REFERENCES COMMISSION (id);

ALTER TABLE WITHDRAW_REQUEST
	ADD CONSTRAINT FK_withdraw_request_admin_holder FOREIGN KEY (admin_holder_id) REFERENCES USER (id);

ALTER TABLE WITHDRAW_REQUEST
	CHANGE COLUMN acceptance acceptance TIMESTAMP NULL DEFAULT NULL;

INSERT INTO USER_COMMENT_TOPIC (topic) VALUES ('WITHDRAW_DECLINE');

INSERT INTO PHRASE_TEMPLATE (template, topic_id) VALUES ('withdrawal.phrases.decline.1', 4);
INSERT INTO PHRASE_TEMPLATE (template, topic_id) VALUES ('withdrawal.phrases.decline.2', 4);
INSERT INTO PHRASE_TEMPLATE (template, topic_id) VALUES ('withdrawal.phrases.decline.3', 4);

ALTER TABLE TRANSACTION
	ADD COLUMN description VARCHAR(100) NULL;
