ALTER TABLE WALLET DROP FOREIGN KEY fk_WALLET_USERS1;
ALTER TABLE WALLET
  ADD CONSTRAINT fk_WALLET_USERS1
FOREIGN KEY (user_id) REFERENCES USER (id) ON DELETE CASCADE;

ALTER TABLE NOTIFICATION_OPTIONS DROP FOREIGN KEY fk_user_id1;
ALTER TABLE NOTIFICATION_OPTIONS
  ADD CONSTRAINT fk_user_id1
FOREIGN KEY (user_id) REFERENCES USER (id) ON DELETE CASCADE;