
DROP TABLE COMPANY_TRANSACTION;

CREATE TABLE `TRANSACTION` (
  `id` int(40) NOT NULL AUTO_INCREMENT,
  `user_wallet_id` int(11) NOT NULL,
  `company_wallet_id` int(11) NOT NULL,
  `amount` double(40,9) NOT NULL,
  `commission_amount` double(40,9) NOT NULL,
  `commission_id` int(11) NOT NULL,
  `operation_type_id` int(11) NOT NULL,
  `currency_id` int(11) NOT NULL,
  `merchant_id` int(11) NOT NULL,
  `datetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_company_UNIQUE` (`id`),
  KEY `fk_COMPANY_ACCOUNT_WALLET1_idx` (`user_wallet_id`),
  KEY `COMPANY_ACCOUNT` (`commission_id`),
  KEY `TRANSACTION_CURRENCY_ID` (`currency_id`),
  KEY `Merchant_id` (`merchant_id`),
  KEY `TRANSACTION` (`operation_type_id`),
  KEY `TRANSACTION_COMPANY_WALLET` (`company_wallet_id`),
  CONSTRAINT `fk_COMPANY_ACCOUNT_WALLET1` FOREIGN KEY (`user_wallet_id`) REFERENCES `WALLET` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `transaction_ibfk_1` FOREIGN KEY (`commission_id`) REFERENCES `COMMISSION` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `transaction_ibfk_3` FOREIGN KEY (`currency_id`) REFERENCES `CURRENCY` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `transaction_ibfk_4` FOREIGN KEY (`merchant_id`) REFERENCES `MERCHANT` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `transaction_ibfk_5` FOREIGN KEY (`operation_type_id`) REFERENCES `OPERATION_TYPE` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `transaction_ibfk_6` FOREIGN KEY (`company_wallet_id`) REFERENCES `COMPANY_WALLET` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=latin1;


ALTER TABLE MERCHANT_CURRENCY ADD COLUMN min_sum DOUBLE(40,9) DEFAULT 0;
LOCK TABLES MERCHANT_CURRENCY WRITE;
UPDATE MERCHANT_CURRENCY SET min_sum = 0.01 WHERE merchant_id = 1 AND currency_id = 1;
UNLOCK TABLES;

ALTER TABLE COMPANY_WALLET ADD COLUMN balance DOUBLE(40,9) NOT NULL DEFAULT 0;
ALTER TABLE COMPANY_WALLET ADD COLUMN commission_balance DOUBLE(40,9) NOT NULL DEFAULT 0;

CREATE TABLE DATABASE_PATCH (version VARCHAR(50), datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP, patched BOOL DEFAULT 0);
LOCK TABLES DATABASE_PATCH WRITE;
INSERT INTO DATABASE_PATCH (version,patched) VALUES ("patch_07_modified_transaction",1);
UNLOCK TABLES;

ALTER TABLE DATABASE_PATCH change column date datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP;