CREATE TABLE SERVICE_ALERTS (
  `alert_type` ENUM('UPDATE', 'TECHNICAL_WORKS') NOT NULL,
  `enable` BOOLEAN NOT NULL DEFAULT FALSE ,
  `time_to_start` TIME DEFAULT NULL,
  `length` TIME DEFAULT NULL,
  `launch_date` TIMESTAMP DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO SERVICE_ALERTS (alert_type, enable, time_to_start, length, launch_date)
VALUES ('UPDATE', FALSE, NULL, NULL, NULL),
  ('TECHNICAL_WORKS', FALSE, NULL, NULL, NULL)