 DROP  TRIGGER IF exists USER_COMMENT_BEFORE_UPD_TR;

DELIMITER ||

CREATE TRIGGER `USER_COMMENT_BEFORE_UPD_TR`
BEFORE UPDATE ON `USER_COMMENT`
FOR EACH ROW
  BEGIN
    IF (NEW.users_comment <> OLD.users_comment) THEN
      SET new.edit_time = CURRENT_TIMESTAMP;
    END IF;
  END||
DELIMITER ;