CREATE TABLE IF NOT EXISTS WITHDRAW_REQUEST (
  transaction_id INT ,
  acceptance TIMESTAMP ,
  wallet VARCHAR(64) NOT NULL ,
  processed_by INT ,
  FOREIGN KEY (transaction_id) REFERENCES TRANSACTION(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (processed_by) REFERENCES USER (id) ON UPDATE CASCADE ON DELETE RESTRICT
);
INSERT INTO DATABASE_PATCH VALUES ('patch_23_add_table_pending_withdraw_request', DEFAULT , 1);
