ALTER TABLE USER ADD COLUMN pin VARCHAR(100) DEFAULT NULL;
ALTER TABLE USER ADD COLUMN use2fa BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE USER ADD COLUMN 2fa_last_notify_date TIMESTAMP NULL DEFAULT NULL;