-- Drop unnecessary tables

DROP TABLE IF EXISTS BCH_ADDRESS_BACKUP;

DROP TABLE IF EXISTS BTC_BALANCE_FOR_BCI;

DROP TABLE IF EXISTS BTC_BALANCE_RESERVE;

DROP TABLE IF EXISTS BTC_TRANSACTION;

DROP TABLE IF EXISTS BTC_TRANSACTION_BACKUP;

DROP TABLE IF EXISTS DATABASE_PATCH;

DROP TABLE IF EXISTS EDC_MERCHANT_ACCOUNT;

DROP TABLE IF EXISTS EDC_MERCHANT_TRANSACTION;

DROP TABLE IF EXISTS EDC_MERCHANT_TRANSACTION_BACKUP;

DROP TABLE IF EXISTS EDC_TEMP_ACCOUNT;

DROP TABLE IF EXISTS EDC_TEMP_ACCOUNT_BACKUP;

DROP TABLE IF EXISTS ETHEREUM_TEMP_ACCOUNT;

DROP TABLE IF EXISTS INVOICE_REQUEST;

DROP TABLE IF EXISTS INVOICE_REQUEST_BACKUP;

DROP TABLE IF EXISTS INVOICE_REQUEST_STATUS;

DROP TABLE IF EXISTS ORDERS;

DROP TABLE IF EXISTS PENDING_PAYMENT;

DROP TABLE IF EXISTS PENDING_PAYMENT_BACKUP;

DROP TABLE IF EXISTS PENDING_PAYMENT_STATUS;

DROP TABLE IF EXISTS REFILL_REQUEST_TEMP;

DROP TABLE IF EXISTS TRANSACTION_BACKUP_REFILL;

DROP TABLE IF EXISTS YANDEX_MONEY_MERCHANT;

DROP TABLE IF EXISTS YANDEX_MONEY_PAYMENT;