ALTER TABLE CURRENCY_PAIR ADD hidden tinyint(1) DEFAULT NULL;

UPDATE CURRENCY_PAIR
SET HIDDEN=true
WHERE name NOT IN (
'BTC/USD',
'EDRC/USD',
'EDRC/RUB',
'EDRC/UAH',
'EDRC/EUR',
'BTC/RUB',
'BTC/UAH',
'BTC/EUR');

UPDATE CURRENCY_PAIR SET pair_order = 1 WHERE name = 'BTC/USD';
UPDATE CURRENCY_PAIR SET pair_order = 2 WHERE name = 'EDRC/USD';
UPDATE CURRENCY_PAIR SET pair_order = 3 WHERE name = 'EDRC/RUB';
UPDATE CURRENCY_PAIR SET pair_order = 4 WHERE name = 'EDRC/UAH';
UPDATE CURRENCY_PAIR SET pair_order = 5 WHERE name = 'EDRC/EUR';
UPDATE CURRENCY_PAIR SET pair_order = 6 WHERE name = 'BTC/RUB';
UPDATE CURRENCY_PAIR SET pair_order = 7 WHERE name = 'BTC/UAH';
UPDATE CURRENCY_PAIR SET pair_order = 8 WHERE name = 'BTC/EUR';


INSERT INTO DATABASE_PATCH VALUES('patch_52_added_field_hidden_in_currency_pair',default,1);