INSERT INTO STOCK_EXCHANGE (name, link) VALUES ('Exrates', 'https://lk.exrates.me/');
INSERT INTO STOCK_CURRENCY_PAIR SELECT STOCK_EXCHANGE.id, CURRENCY_PAIR.id FROM STOCK_EXCHANGE
  JOIN CURRENCY_PAIR
WHERE STOCK_EXCHANGE.name = 'Exrates' AND (CURRENCY_PAIR.hidden IS NULL OR CURRENCY_PAIR.hidden != 1);
