DROP TABLE IF EXISTS TRANSACTION_STATUS;

CREATE TABLE TRANSACTION_STATUS (
  `id` int(40) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL,
  `description` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

INSERT INTO TRANSACTION_STATUS
VALUES (1, 'created', ''), (2, 'deleted', 'deleted by admin');

ALTER TABLE TRANSACTION
ADD COLUMN status_id int(11) NOT NULL DEFAULT '1';

ALTER TABLE TRANSACTION
ADD KEY status_id (status_id);

ALTER TABLE TRANSACTION
ADD CONSTRAINT transaction_status_fk FOREIGN KEY (status_id) REFERENCES TRANSACTION_STATUS (id) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE TRANSACTION
ADD COLUMN status_modification_date timestamp;

DELIMITER ;;
CREATE TRIGGER TRANSACTION_BEFORE_UPD_TR BEFORE UPDATE ON TRANSACTION
FOR EACH ROW
  BEGIN
    IF (NEW.status_id <> OLD.status_id) THEN
      SET new.status_modification_date = CURRENT_TIMESTAMP;
    END IF;
  END;;
DELIMITER ;

ALTER TABLE EXORDERS
ADD COLUMN status_modification_date timestamp;

DELIMITER ;;
CREATE TRIGGER EXORDERS_BEFORE_UPD_TR BEFORE UPDATE ON EXORDERS
FOR EACH ROW
  BEGIN
    IF (NEW.status_id <> OLD.status_id) THEN
      SET new.status_modification_date = CURRENT_TIMESTAMP;
    END IF;
  END;;
DELIMITER ;

INSERT INTO DATABASE_PATCH VALUES('patch_39_for_order_deletion',default,1);