CREATE TABLE API_TEMP_PASSWORD (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `date_creation` TIMESTAMP NULL,
  `temporal_token_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`)
  REFERENCES USER (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  FOREIGN KEY (`temporal_token_id`)
  REFERENCES TEMPORAL_TOKEN (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);

INSERT INTO DATABASE_PATCH VALUES('patch_67_add_api_temp_password',default,1);