ALTER TABLE WITHDRAW_REQUEST
	ADD COLUMN amount DOUBLE(40,9) NULL DEFAULT NULL,
	ADD COLUMN commission DOUBLE(40,9) NULL DEFAULT NULL,
	ADD COLUMN date_creation TIMESTAMP NULL DEFAULT NULL;

ALTER TABLE WITHDRAW_REQUEST
	ADD COLUMN id INT(11) NOT NULL AUTO_INCREMENT FIRST,
	ADD PRIMARY KEY (id);

CREATE TABLE WITHDRAW_REQUEST_STATUS (
	id INT(11) NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (id)
)
ENGINE=InnoDB;

INSERT INTO WITHDRAW_REQUEST_STATUS (id, name) VALUES (1, 'CREATED_USER');
INSERT INTO WITHDRAW_REQUEST_STATUS (id, name) VALUES (2, 'WAITING_MANUAL_POSTING');
INSERT INTO WITHDRAW_REQUEST_STATUS (id, name) VALUES (3, 'WAITING_AUTO_POSTING');
INSERT INTO WITHDRAW_REQUEST_STATUS (id, name) VALUES (4, 'WAITING_CONFIRMATION');
INSERT INTO WITHDRAW_REQUEST_STATUS (id, name) VALUES (5, 'IN_WORK_OF_ADMIN');
INSERT INTO WITHDRAW_REQUEST_STATUS (id, name) VALUES (6, 'WAITING_CONFIRMED_POSTING');
INSERT INTO WITHDRAW_REQUEST_STATUS (id, name) VALUES (7, 'REVOKED_USER');
INSERT INTO WITHDRAW_REQUEST_STATUS (id, name) VALUES (8, 'DECLINED_ADMIN');
INSERT INTO WITHDRAW_REQUEST_STATUS (id, name) VALUES (9, 'POSTED_MANUAL');
INSERT INTO WITHDRAW_REQUEST_STATUS (id, name) VALUES (10, 'POSTED_AUTO');


ALTER TABLE WITHDRAW_REQUEST
	ADD COLUMN status_id INT(11) NULL DEFAULT NULL,
	ADD COLUMN status_modification_date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;
	
ALTER TABLE WITHDRAW_REQUEST
	ADD CONSTRAINT FK_withdraw_request_withdraw_request_status FOREIGN KEY (status_id) REFERENCES WITHDRAW_REQUEST_STATUS (id);

