
ALTER TABLE BOT_TRADING_SETTINGS ADD min_price_deviation INT DEFAULT 0 NOT NULL;
ALTER TABLE BOT_TRADING_SETTINGS ADD max_price_deviation INT DEFAULT 0 NOT NULL;
ALTER TABLE BOT_TRADING_SETTINGS ADD randomize_price_step TINYINT(1) DEFAULT 0 NOT NULL;
ALTER TABLE BOT_TRADING_SETTINGS ADD price_step_deviation INT DEFAULT 0 NOT NULL;