ALTER TABLE USER_COMMENT ADD creation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL AFTER user_creator_id;
UPDATE USER_COMMENT SET creation_time = edit_time;

DELIMITER ||
CREATE TRIGGER `USER_COMMENT_BEFORE_UPD_TR`
BEFORE UPDATE ON `USER_COMMENT`
FOR EACH ROW
  BEGIN
    IF (NEW.users_comment <> OLD.users_comment) THEN
      SET new.edit_time = CURRENT_TIMESTAMP;
    END IF;
  END||
DELIMITER ;