ALTER TABLE USER_ROLE_SETTINGS ADD use_real_money TINYINT(1) DEFAULT 1 NOT NULL;
UPDATE USER_ROLE_SETTINGS SET use_real_money = 0 WHERE user_role_id IN (8, 10);

CREATE TABLE REPORT_MAILING_PARAMS
(
  id INT PRIMARY KEY AUTO_INCREMENT,
  param_name VARCHAR(50) NOT NULL,
  param_value VARCHAR(100) NOT NULL
);
CREATE UNIQUE INDEX report_mailing_params_param_name_uindex ON REPORT_MAILING_PARAMS (param_name);

INSERT INTO REPORT_MAILING_PARAMS (param_name, param_value) VALUES ('ENABLE_REPORT_MAILING', 'true');
INSERT INTO REPORT_MAILING_PARAMS (param_name, param_value) VALUES ('MAIL_TIME', '00:00');

CREATE TABLE REPORT_SUBSCRIBERS
(
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(50) NOT NULL
);
CREATE UNIQUE INDEX REPORT_SUBSCRIBERS_email_uindex ON REPORT_SUBSCRIBERS (email);


