INSERT INTO API_PARAMS (param_name, param_value) VALUES ('KEY_CHECK_ENABLED', 'OFF');

ALTER TABLE STOCK_EXRATE MODIFY price_last DOUBLE(40,9);
ALTER TABLE STOCK_EXRATE MODIFY price_buy DOUBLE(40,9);
ALTER TABLE STOCK_EXRATE MODIFY price_sell DOUBLE(40,9);
ALTER TABLE STOCK_EXRATE MODIFY price_low DOUBLE(40,9);
ALTER TABLE STOCK_EXRATE MODIFY price_high DOUBLE(40,9);
ALTER TABLE STOCK_EXRATE MODIFY volume DOUBLE(40,9);