CREATE TABLE NOTIFICATOR
(
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `bean_name` VARCHAR(256) NOT NULL,
  `pay_type` ENUM('FREE', 'PREPAID_LIFETIME', 'PAY_FOR_EACH') NOT NULL,
  `message_cost` DECIMAL(40,9) NULL DEFAULT NULL,
  `subscribe_cost` DECIMAL(40,9) NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO NOTIFICATOR VALUES (1, 'SmsNotificatorServiceImpl', 'FREE', NULL, NULL);

CREATE TABLE NOTIFICATION_MESSAGES
(
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `event` VARCHAR(64) NOT NULL,
  `type` VARCHAR(64) NOT NULL,
  `message` VARCHAR(512) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE NOTIFICATION_LOG
(
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `email` VARCHAR(64) NOT NULL,
  `type` VARCHAR(64) NOT NULL,
  `event` VARCHAR(64) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `payed_amount` DECIMAL(40,9) NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE USER_NOTIFICATION_MESSAGE_SETTINGS
(
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `user_id`  INT NOT NULL,
  `notificator_id`  INT NOT NULL,
  `event_name` ENUM('LOGIN', 'WITHDRAW', 'TRANSFER') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE (`user_id`, `notificator_id`),
  INDEX `USER_NOTIFICATION_MESSAGE_SETTINGS_user_id` (`user_id`),
  INDEX `USER_NOTIFICATION_MESSAGE_SETTINGS_notificator_id` (`notificator_id`),
  CONSTRAINT `fk_USER_NOTIFICATION_MESSAGE_SETTINGS_user_id` FOREIGN KEY (`user_id`) REFERENCES `USER` (`id`),
  CONSTRAINT `fk_USER_NOTIFICATION_MESSAGE_SETTINGS_notificator_id` FOREIGN KEY (`notificator_id`) REFERENCES `NOTIFICATOR` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;