INSERT INTO USER_COMMENT_TOPIC (id, topic) VALUES (10, 'REFILL_MERCHANT_WARNING');
INSERT INTO USER_COMMENT_TOPIC (id, topic) VALUES (11, 'WITHDRAW_MERCHANT_WARNING');
INSERT INTO PHRASE_TEMPLATE(template, topic_id) VALUES ('input.warning.Payeer', 10);