
INSERT INTO REFILL_REQUEST_STATUS (id, name) VALUES (15, 'ON_INNER_TRANSFERRING');
INSERT INTO REFILL_REQUEST_STATUS (id, name) VALUES (16, 'WAITING_REVIEWING');
INSERT INTO REFILL_REQUEST_STATUS (id, name) VALUES (17, 'TAKEN_FOR_REFILL');

INSERT INTO WITHDRAW_REQUEST_STATUS (id, name) VALUES (13, 'ON_BCH_EXAM');
INSERT INTO WITHDRAW_REQUEST_STATUS (id, name) VALUES (14, 'WAITING_REVIEWING');
INSERT INTO WITHDRAW_REQUEST_STATUS (id, name) VALUES (15, 'TAKEN_FOR_WITHDRAW');

ALTER TABLE REFILL_REQUEST ADD INDEX merchant_id_merchant_transaction_id (merchant_id, merchant_transaction_id);