ALTER TABLE CHAT_EN
ADD COLUMN message_time DATETIME NOT NULL AFTER body;
ALTER TABLE CHAT_RU
ADD COLUMN message_time DATETIME NOT NULL AFTER body;
ALTER TABLE CHAT_CN
ADD COLUMN message_time DATETIME NOT NULL AFTER body;

UPDATE CHAT_EN SET message_time = '2016-08-22 00:00:00';
UPDATE CHAT_RU SET message_time = '2016-08-22 00:00:00';
UPDATE CHAT_CN SET message_time = '2016-08-22 00:00:00';

INSERT INTO DATABASE_PATCH VALUES('patch_54_add_datetime_to_chats',default,1);