ALTER TABLE WITHDRAW_REQUEST
	ADD COLUMN currency_id INT(11) NULL DEFAULT NULL,
	ADD COLUMN user_id INT(11) NULL DEFAULT NULL,
	ADD COLUMN commission INT(11) NULL DEFAULT NULL,
	ADD COLUMN merchant_id INT(11) NULL DEFAULT NULL;

ALTER TABLE WITHDRAW_REQUEST
	ADD CONSTRAINT FK_withdraw_request_currency FOREIGN KEY (currency_id) REFERENCES CURRENCY (id);

ALTER TABLE WITHDRAW_REQUEST
	ADD CONSTRAINT FK_withdraw_request_merchant FOREIGN KEY (merchant_id) REFERENCES MERCHANT (id);

ALTER TABLE WITHDRAW_REQUEST
	ADD CONSTRAINT FK_withdraw_request_user FOREIGN KEY (user_id) REFERENCES USER (id);

ALTER TABLE WITHDRAW_REQUEST
	ADD CONSTRAINT FK_withdraw_request_commission FOREIGN KEY (commission_id) REFERENCES COMMISSION (id);

