CREATE TABLE IF NOT EXISTS USER_DOC (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT,
  path VARCHAR(64) NOT NULL UNIQUE ,
  FOREIGN KEY USER_DOCS(user_id) REFERENCES USER(id) ON UPDATE CASCADE ON DELETE CASCADE
);