ALTER TABLE CURRENCY_PAIR_LIMIT ADD min_amount DECIMAL(40,9) DEFAULT 0.0000001 NOT NULL;
ALTER TABLE CURRENCY_PAIR_LIMIT ADD max_amount DECIMAL(40,9) DEFAULT 9999999999 NOT NULL;

INSERT INTO BOT_LAUNCH_SETTINGS(bot_trader_id, currency_pair_id)
    SELECT BT.id, CP.id FROM BOT_TRADER BT
JOIN CURRENCY_PAIR CP WHERE CP.name IN ('EOS/USD', 'EOS/BTC', 'REP/USD', 'REP/BTC');

INSERT INTO BOT_TRADING_SETTINGS(bot_launch_settings_id, order_type_id) 
    SELECT BLCH.id, OT.id FROM BOT_LAUNCH_SETTINGS BLCH
JOIN ORDER_TYPE OT 
WHERE BLCH.currency_pair_id IN (SELECT id FROM CURRENCY_PAIR WHERE name IN ('EOS/USD', 'EOS/BTC', 'REP/USD', 'REP/BTC'));
