
DROP TABLE IF EXISTS `CURRENCY_PAIR`;
CREATE TABLE IF NOT EXISTS `birzha`.`CURRENCY_PAIR` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `currency1_id` int(11) NOT NULL,
  `currency2_id` int(11) NOT NULL,
  `name` varchar(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

INSERT INTO `CURRENCY_PAIR` VALUES (1,2,1,'USD/RUR');
INSERT INTO DATABASE_PATCH (version,patched) VALUES ("patch_09_create_currencyPair",1);