ALTER TABLE CURRENCY_PAIR ADD COLUMN scale INT(11) NULL;

UPDATE CURRENCY_PAIR SET scale = 2 WHERE market = 'FIAT';
UPDATE CURRENCY_PAIR SET scale = 2 WHERE market = 'USD';
UPDATE CURRENCY_PAIR SET scale = 8 WHERE market = 'BTC';
UPDATE CURRENCY_PAIR SET scale = 8 WHERE market = 'ETH';