ALTER TABLE CURRENCY_LIMIT ADD COLUMN min_sum_usd DOUBLE(40, 9) NOT NULL DEFAULT 0 AFTER min_sum;
ALTER TABLE CURRENCY_LIMIT ADD COLUMN usd_rate NUMERIC(19, 8) NOT NULL DEFAULT 0 AFTER min_sum_usd;
ALTER TABLE CURRENCY_LIMIT ADD recalculate_to_usd TINYINT(1) NOT NULL DEFAULT false;