ALTER TABLE USER_VERIFICATION_DOCS DROP FOREIGN KEY user_verification_docs_ibfk_1;

DROP TABLE IF EXISTS USER_VERIFICATION_INFO;

CREATE TABLE USER_VERIFICATION_INFO (
  user_id INTEGER NOT NULL,
  document_type enum ('ID', 'P') NOT NULL,
  doc_id VARCHAR(255)
  )
  ENGINE = InnoDB;

ALTER TABLE USER_VERIFICATION_INFO
  ADD CONSTRAINT pk_user_verification_info PRIMARY KEY (user_id, document_type);

ALTER TABLE USER_VERIFICATION_INFO
  ADD CONSTRAINT fk_user_id_on_user_verification_info FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE;