DROP TABLE USER_VERIFICATION_INFO ;

CREATE TABLE USER_VERIFICATION_INFO (
  user_id INTEGER NOT NULL,
  doc_type ENUM ('ID', 'P') NOT NULL DEFAULT 'P',
  doc_id VARCHAR(55))
  ENGINE = InnoDB;

ALTER TABLE USER_VERIFICATION_INFO
  ADD CONSTRAINT fk_user_id_on_user_verification_info FOREIGN KEY (user_id) REFERENCES USER(id) ON DELETE CASCADE;