CREATE TABLE IF NOT EXISTS SYNDEX_ORDER (
    refill_request_id               INT(11) PRIMARY KEY          NOT NULL,
    syndex_id                       INT UNSIGNED,
    status_modification_date        TIMESTAMP DEFAULT NOW()      NOT NULL,
    payment_details_received_date   TIMESTAMP NULL,
    user_id                         INT(40)                      NOT NULL,
    confirmed                       TINYINT(1) DEFAULT FALSE     NOT NULL,
    amount                          DOUBLE(40, 8)                NOT NULL,
    status_id                       INT UNSIGNED                 NOT NULL,
    commission                      DOUBLE(40, 8)                NOT NULL,
    payment_system_id               VARCHAR(200)                 NOT NULL,
    currency                        VARCHAR(20)                  NOT NULL,
    country_id                      VARCHAR(20)                  NOT NULL,
    payment_details                 TEXT                CHARACTER SET utf8 COLLATE utf8_unicode_ci,
    dispute_details                 TEXT                CHARACTER SET utf8 COLLATE utf8_unicode_ci,
    payment_time_end                TIMESTAMP NULL,
    FOREIGN KEY syndex_order_ref_req_fk(refill_request_id) REFERENCES REFILL_REQUEST(id),
    FOREIGN KEY syndex_order_user_id_fk(user_id) REFERENCES USER(id),
    index (syndex_id)
)
