DROP TABLE IF EXISTS KYC_COUNTRY_CODES;

CREATE TABLE KYC_COUNTRY_CODES
(
  id                INT(40) UNSIGNED PRIMARY KEY   NOT NULL AUTO_INCREMENT,
  country_name      VARCHAR(64)                    NOT NULL,
  country_code      VARCHAR(2)                     NOT NULL
);

DROP TABLE IF EXISTS KYC_LANGUAGE_CODES;

CREATE TABLE KYC_LANGUAGE_CODES
(
  id                 INT(40) UNSIGNED PRIMARY KEY   NOT NULL AUTO_INCREMENT,
  language_name      VARCHAR(64)                    NOT NULL,
  language_code      VARCHAR(2)                     NOT NULL
);

INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Aland Islands', 'AX');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Albania', 'AL');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Algeria', 'DZ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('American Samoa', 'AS');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Andorra', 'AD');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Angola', 'AO');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Anguilla', 'AI');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Antarctica', 'AQ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Antigua and Barbuda', 'AG');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Argentina', 'AR');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Armenia', 'AM');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Aruba', 'AW');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Australia', 'AU');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Austria', 'AT');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Azerbaijan', 'AZ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Bahamas', 'BS');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Bahrain', 'BH');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Bangladesh', 'BD');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Barbados', 'BB');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Belarus', 'BY');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Belgium', 'BE');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Belize', 'BZ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Benin', 'BJ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Bermuda', 'BM');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Bhutan', 'BT');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Bolivia', 'BO');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Bosnia and Herzegovina', 'BA');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Botswana', 'BW');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Bouvet Island', 'BV');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Brazil', 'BR');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('British Indian Ocean Territory', 'IO');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Brunei', 'BN');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Bulgaria', 'BG');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Burkina Faso', 'BF');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Burma (Myanmar)', 'MM');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Burundi', 'BI');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Cambodia', 'KH');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Cameroon', 'CM');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Canada', 'CA');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Cape Verde', 'CV');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Cayman Islands', 'KY');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Central African Republic', 'CF');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Chad', 'TD');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Chile', 'CL');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('China', 'CN');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Christmas Island', 'CX');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Cocos (Keeling) Islands', 'CC');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Colombia', 'CO');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Comoros', 'KM');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Congo,  Dem. Republic', 'CD');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Congo,  Republic', 'CG');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Cook Islands', 'CK');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Costa Rica', 'CR');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Croatia', 'HR');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Cuba', 'CU');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Cyprus', 'CY');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Czech Republic', 'CZ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Denmark', 'DK');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Djibouti', 'DJ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Dominica', 'DM');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Dominican Republic', 'DO');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('East Timor', 'TL');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Ecuador', 'EC');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Egypt', 'EG');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('El Salvador', 'SV');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Equatorial Guinea', 'GQ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Eritrea', 'ER');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Estonia', 'EE');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Ethiopia', 'ET');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Falkland Islands', 'FK');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Faroe Islands', 'FO');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Fiji', 'FJ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Finland', 'FI');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('France', 'FR');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('French Guiana', 'GF');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('French Polynesia', 'PF');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('French Southern Territories', 'TF');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Gabon', 'GA');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Gambia', 'GM');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Georgia', 'GE');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Germany', 'DE');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Ghana', 'GH');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Gibraltar', 'GI');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Greece', 'GR');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Greenland', 'GL');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Grenada', 'GD');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Guadeloupe', 'GP');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Guam', 'GU');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Guatemala', 'GT');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Guernsey', 'GG');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Guinea', 'GN');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Guinea-Bissau', 'GW');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Guyana', 'GY');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Haiti', 'HT');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Heard Island and McDonald Islands', 'HM');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Honduras', 'HN');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('HongKong', 'HK');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Hungary', 'HU');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Iceland', 'IS');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('India', 'IN');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Indonesia', 'ID');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Iran', 'IR');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Iraq', 'IQ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Ireland', 'IE');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Israel', 'IL');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Italy', 'IT');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Ivory Coast', 'CI');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Jamaica', 'JM');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Japan', 'JP');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Jersey', 'JE');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Jordan', 'JO');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Kazakhstan', 'KZ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Kenya', 'KE');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Kiribati', 'KI');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Korea,  Dem. Republic of', 'KP');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Kuwait', 'KW');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Kyrgyzstan', 'KG');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Laos', 'LA');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Latvia', 'LV');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Lebanon', 'LB');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Lesotho', 'LS');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Liberia', 'LR');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Libya', 'LY');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Liechtenstein', 'LI');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Lithuania', 'LT');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Luxemburg', 'LU');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Macau', 'MO');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Macedonia', 'MK');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Madagascar', 'MG');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Malawi', 'MW');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Malaysia', 'MY');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Maldives', 'MV');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Mali', 'ML');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Malta', 'MT');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Man Island', 'IM');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Marshall Islands', 'MH');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Martinique', 'MQ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Mauritania', 'MR');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Mauritius', 'MU');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Mayotte', 'YT');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Mexico', 'MX');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Micronesia', 'FM');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Moldova', 'MD');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Monaco', 'MC');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Mongolia', 'MN');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Montenegro', 'ME');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Montserrat', 'MS');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Morocco', 'MA');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Mozambique', 'MZ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Namibia', 'NA');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Nauru', 'NR');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Nepal', 'NP');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Netherlands', 'NL');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Netherlands Antilles', 'AN');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('New Caledonia', 'NC');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('New Zealand', 'NZ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Nicaragua', 'NI');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Niger', 'NE');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Nigeria', 'NG');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Niue', 'NU');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Norfolk Island', 'NF');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Northern Mariana Islands', 'MP');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Norway', 'NO');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Oman', 'OM');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Pakistan', 'PK');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Palau', 'PW');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Palestinian Territories', 'PS');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Panama', 'PA');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Papua New Guinea', 'PG');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Paraguay', 'PY');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Peru', 'PE');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Philippines', 'PH');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Pitcairn', 'PN');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Poland', 'PL');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Portugal', 'PT');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Puerto Rico', 'PR');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Qatar', 'QA');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Reunion Island', 'RE');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Romania', 'RO');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Russian Federation', 'RU');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Rwanda', 'RW');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Saint Barthelemy', 'BL');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Saint Kitts and Nevis', 'KN');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Saint Lucia', 'LC');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Saint Martin', 'MF');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Saint Pierre and Miquelon', 'PM');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Saint Vincent and the Grenadines', 'VC');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Samoa', 'WS');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('San Marino', 'SM');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Saudi Arabia', 'SA');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Senegal', 'SN');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Serbia', 'RS');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Seychelles', 'SC');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Sierra Leone', 'SL');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Singapore', 'SG');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Slovakia', 'SK');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Slovenia', 'SI');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Solomon Islands', 'SB');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Somalia', 'SO');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('South Africa', 'ZA');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('South Georgia and the South Sandwich Islands', 'GS');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('South Korea', 'KR');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Spain', 'ES');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Sri Lanka', 'LK');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Sudan', 'SD');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Suriname', 'SR');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Svalbard and Jan Mayen', 'SJ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Swaziland', 'SZ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Sweden', 'SE');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Switzerland', 'CH');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Syria', 'SY');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('São Tomé and Príncipe', 'ST');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Taiwan', 'TW');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Tajikistan', 'TJ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Tanzania', 'TZ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Thailand', 'TH');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Togo', 'TG');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Tokelau', 'TK');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Tonga', 'TO');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Trinidad and Tobago', 'TT');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Tunisia', 'TN');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Turkey', 'TR');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Turkmenistan', 'TM');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Turks and Caicos Islands', 'TC');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Tuvalu', 'TV');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Uganda', 'UG');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Ukraine', 'UA');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('United Arab Emirates', 'AE');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('United Kingdom', 'GB');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('United States', 'US');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Uruguay', 'UY');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Uzbekistan', 'UZ');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Vanuatu', 'VU');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Vatican City State', 'VA');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Venezuela', 'VE');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Vietnam', 'VN');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Virgin Islands (British)', 'VG');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Virgin Islands (U.S.)', 'VI');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Wallis and Futuna', 'WF');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Western Sahara', 'EH');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Yemen', 'YE');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Zambia', 'ZM');
INSERT IGNORE INTO KYC_COUNTRY_CODES(country_name, country_code) VALUES ('Zimbabwe', 'ZW');

INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Albanian', 'SQ');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Amharic', 'AM');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Arabic', 'AR');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Armenian', 'HY');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Azerbaijani', 'AZ');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Basque', 'EU');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Belarusian', 'BE');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Bengali', 'BN');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Bosnian', 'BS');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Bulgarian', 'BG');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Burmese', 'MY');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Catalan', 'CA');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Chichewa', 'NY');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Chinese', 'ZH');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Corsican', 'CO');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Croatian', 'HR');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Czech', 'CS');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Danish', 'DA');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Dutch', 'NL');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('English', 'EN');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Esperanto', 'EO');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Estonian', 'ET');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Filipino', 'TL');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Finnish', 'FI');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('French', 'FR');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Frisian', 'FY');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Galician', 'GL');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Georgian', 'KA');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('German', 'DE');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Greek (modern)', 'EL');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Gujarati', 'GU');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Haitian,  Haitian Creole', 'HT');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Hausa', 'HA');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Hebrew (modern)', 'HE');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Hindi', 'HI');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Hungarian', 'HU');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Icelandic', 'IS');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Igbo', 'IG');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Indonesian', 'ID');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Irish', 'GA');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Italian', 'IT');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Japanese', 'JA');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Javanese', 'JV');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Kannada', 'KN');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Kazakh', 'KK');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Khmer', 'KM');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Kirghiz,  Kyrgyz', 'KY');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Korean', 'KO');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Kurdish', 'KU');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Lao', 'LO');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Latin', 'LA');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Latvian', 'LV');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Lithuanian', 'LT');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Luxembourgish,  Letzeburgesch', 'LB');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Macedonian', 'MK');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Malagasy', 'MG');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Malay', 'MS');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Malayalam', 'ML');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Maltese', 'MT');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Maori', 'MI');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Marathi', 'MR');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Mongolian', 'MN');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Nepali', 'NE');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Norwegian', 'NO');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Pashto', 'PS');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Persian', 'FA');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Polish', 'PL');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Portuguese', 'PT');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Punjabi', 'PA');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Romanian', 'RO');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Russian', 'RU');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Samoan', 'SM');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Scottish Gaelic', 'GD');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Serbian', 'SR');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Sesotho', 'ST');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Shona', 'SN');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Sindhi', 'SD');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Sinhala', 'SI');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Slovak', 'SK');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Slovenian', 'SL');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Somali', 'SO');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Spanish', 'ES');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Sundanese', 'SU');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Swahili', 'SW');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Swedish', 'SV');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Tajik', 'TG');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Tamil', 'TA');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Telugu', 'TE');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Thai', 'TH');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Turkish', 'TR');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Ukrainian', 'UK');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Urdu', 'UR');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Uzbek', 'UZ');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Vietnamese', 'VI');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Welsh', 'CY');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Xhosa', 'XH');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Yiddish', 'YI');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Yoruba', 'YO');
INSERT IGNORE INTO KYC_LANGUAGE_CODES(language_name, language_code) VALUES ('Zulu', 'ZU');