ALTER TABLE COMPANY_EXTERNAL_WALLET_BALANCES CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE COMPANY_WALLET_EXTERNAL_RESERVED_ADDRESS CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE INTERNAL_WALLET_BALANCES CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE BALANCES_REPORT CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;