DROP PROCEDURE IF EXISTS `Alter_Table`;

DELIMITER ;;
CREATE PROCEDURE `Alter_Table`()
BEGIN

    IF NOT EXISTS( SELECT NULL
                   FROM INFORMATION_SCHEMA.COLUMNS
                   WHERE table_name = 'COMPANY_WALLET_EXTERNAL_RESERVED_ADDRESS'
                     AND column_name = 'name')  THEN

        ALTER TABLE COMPANY_WALLET_EXTERNAL_RESERVED_ADDRESS ADD COLUMN name VARCHAR(200) NULL AFTER currency_id;

    END IF;

END ;;
DELIMITER ;

CALL Alter_Table();

DROP PROCEDURE `Alter_Table`;
