CREATE TABLE IF NOT EXISTS USER_VERIFICATION_INFO (
  user_id INT NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  born DATE NOT NULL,
  residential_address VARCHAR(255),
  postal_code VARCHAR(10),
  country VARCHAR(50),
  city VARCHAR(50),
  PRIMARY KEY (user_id)
) DEFAULT CHARACTER SET = utf8;


CREATE TABLE IF NOT EXISTS USER_VERIFICATION_DOCS (
  user_id INT NOT NULL,
  document_type ENUM ('PASSPORT', 'IDENTITY_CARD', 'DRIVER_LICENSE', 'PHOTO') DEFAULT 'PASSPORT',
  image_encoded LONGBLOB NOT NULL,
  PRIMARY KEY (user_id, document_type),
  FOREIGN KEY (user_id) REFERENCES USER_VERIFICATION_INFO(user_id) ON DELETE CASCADE ON UPDATE NO ACTION
) DEFAULT CHARACTER SET = utf8;