ALTER TABLE CALLBACK_SETTINGS ADD COLUMN `PAIR_ID` INT(20);

ALTER TABLE CALLBACK_SETTINGS DROP PRIMARY KEY, ADD PRIMARY KEY(`USER_ID`, `PAIR_ID`);

ALTER TABLE CALLBACK_SETTINGS ADD CONSTRAINT pair_id_UNIQUE UNIQUE (`PAIR_ID`);

ALTER TABLE CALLBACK_SETTINGS ADD CONSTRAINT fk_pair_id_currency_pair FOREIGN KEY (`PAIR_ID`) REFERENCES CURRENCY_PAIR(id);
