DROP TABLE CALLBACK_SETTINGS;

CREATE TABLE IF NOT EXISTS `CALLBACK_SETTINGS` (
  `USER_ID`      int(11)      NOT NULL AUTO_INCREMENT,
  `CALLBACK_URL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `id_UNIQUE` (`USER_ID`),
  FOREIGN KEY (USER_ID) REFERENCES USER (id)
) CHARACTER SET utf8 COLLATE utf8_general_ci;


ALTER TABLE CALLBACK_SETTINGS ADD COLUMN `PAIR_ID` INT(20);

ALTER TABLE CALLBACK_SETTINGS DROP PRIMARY KEY, ADD PRIMARY KEY(`USER_ID`, `PAIR_ID`);

ALTER TABLE CALLBACK_SETTINGS ADD FOREIGN KEY (`PAIR_ID`) REFERENCES CURRENCY_PAIR(id);

ALTER TABLE CALLBACK_SETTINGS DROP INDEX id_UNIQUE;
