CREATE TABLE IF NOT EXISTS `USER_OPERATION` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) DEFAULT NULL,
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
);

INSERT IGNORE INTO USER_OPERATION (name) VALUES ('INPUT');

INSERT IGNORE INTO USER_OPERATION (name) VALUES ('OUTPUT');

INSERT IGNORE INTO USER_OPERATION (name) VALUES ('TRANSFER');

INSERT IGNORE INTO USER_OPERATION (name) VALUES ('TRADING');

CREATE TABLE IF NOT EXISTS `USER_OPERATION_AUTHORITY` (
  `user_id` int(11) NOT NULL,
  `user_operation_id` int(11) NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`,`user_operation_id`)
);

INSERT IGNORE INTO USER_OPERATION_AUTHORITY (user_id, user_operation_id) SELECT id, (SELECT id FROM USER_OPERATION WHERE id=1) FROM USER;

INSERT IGNORE INTO USER_OPERATION_AUTHORITY (user_id, user_operation_id) SELECT id, (SELECT id FROM USER_OPERATION WHERE id=2) FROM USER;

INSERT IGNORE INTO USER_OPERATION_AUTHORITY (user_id, user_operation_id) SELECT id, (SELECT id FROM USER_OPERATION WHERE id=3) FROM USER;

INSERT IGNORE INTO USER_OPERATION_AUTHORITY (user_id, user_operation_id) SELECT id, (SELECT id FROM USER_OPERATION WHERE id=4) FROM USER;
