ALTER TABLE TELEGRAM_CHAT_EN ADD COLUMN message_id INT(11) NOT NULL AFTER id;

ALTER TABLE TELEGRAM_CHAT_EN ADD COLUMN message_reply_id INT(11) NULL AFTER message_time;

ALTER TABLE TELEGRAM_CHAT_EN ADD COLUMN telegram_user_id INT(11) NOT NULL AFTER chat_id;

ALTER TABLE TELEGRAM_CHAT_EN ADD COLUMN telegram_user_reply_id INT(11) NULL AFTER message_time;